name: Main

on: [push]

jobs:
  build-test-and-deploy:
    name: Build, Test and Deploy
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Setup Node 10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Setup Bundler
      run: |
        gem install bundler
        bundle install --path=.bundler --jobs $(nproc)
    - name: Build
      run: |
        export LANG=en_US.UTF-8
        export LANGUAGE=en_US:en
        export LC_ALL=en_US.UTF-8
        bundle exec nanoc compile
    - name: Stats
      run: |
        du -shc output/* | sort -h
        echo "$(find output -type f | wc -l | tr -d ' ') generated files"
    - name: Test
      run: |
        bundle exec nanoc check ilinks stale
    - name: Deploy
      env:
        GIT_SHA: ${{ github.sha }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        npm install --prefix .npm firebase-tools
        .npm/node_modules/.bin/firebase deploy --only hosting:opatry-website -m "GitHub Actions@${GIT_SHA::8}" --token "$FIREBASE_TOKEN" --non-interactive
      if: github.ref == 'refs/heads/master'
